### ISSUE TITLE
Alejandro- Identify bug to be fixed/Feature to implement

### ISSUE THREAD

**Issue by Ale-Torres** [samuel-barrett/pytest#1]
Identify Enhancement to implement for M3

**Comment by ekanemeinstein** [comment]
- [ ]  Recreate issue locally or otherwise
- [ ]  Create issue for selected issue
- [ ]  Add link to issue in this issue

**Comment by Ale-Torres** [comment]
link to issue

https://github.com/pytest-dev/pytest/issues/9515

**Comment by Ale-Torres** [comment]
Added commit to wrong issue this issue was to identify the issue. Issue #2  is where commits are meant and will take place
