### ISSUE TITLE
Stop testing a file on first fail

### ISSUE THREAD

**Issue by Ale-Torres** [samuel-barrett/pytest#2]
What's the problem this feature will solve?
This allows me to gather all failed files quicker, I don't need to know whether the remaining tests passed in this file.

Describe the solution you'd like
This will be equivalent to the -x option, but on a per-file basis. That is, pytest stops testing this file if it has one failed test.

This can save time when running on clouds like Github Action, if it fails fast, then I'll be charged less, knowing I have to re-run them.

Alternative Solutions
I'm not sure which plugin can solve this problem.

Additional context

[Link to original Issue](https://github.com/pytest-dev/pytest/issues/9515)

**Comment by ekanemeinstein** [comment]
- [ ]  Create fix branch
- [ ]  Write code fix
- [ ]  Test code fix
- [ ]  Commit code fix
- [ ]  Create PR
- [ ]  Approval/Merge
